services:
  frontend:
    build: ./frontend
    command: npm run serve
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./lab_4_front/src:/usr/src/app/src
  #      - ./frontend/src/main.js:/usr/src/app/src/main.js

  backend-db:
    image: postgres:latest
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    command: postgres -c log_statement=all

  backend:
    build: ./backend
    command: java -jar app.jar
    restart: unless-stopped
    environment:
#      - 'PG_DB_URL=jdbc:postgresql://backend-db:5432/postgres'
#      - 'PG_DB_USERNAME=postgres'
#      - 'PG_DB_PASSWORD=postgres'
      - 'SERVER_PORT=8080'
    depends_on:
      - backend-db

